-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema videogamedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `videogamedb` ;

-- -----------------------------------------------------
-- Schema videogamedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videogamedb` DEFAULT CHARACTER SET utf8 ;
USE `videogamedb` ;

-- -----------------------------------------------------
-- Table `game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

CREATE TABLE IF NOT EXISTS `game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `original_platform` VARCHAR(100) NULL,
  `released_year` INT NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT 'No description yet',
  `image` VARCHAR(200) NULL DEFAULT 'No image yet',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS videogameuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'videogameuser'@'localhost' IDENTIFIED BY 'videogameuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'videogameuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `game`
-- -----------------------------------------------------
START TRANSACTION;
USE `videogamedb`;
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (1, 'Pong', 'Sports', 'Atari', 'Arcade', 1972, 'Pong is a two-dimensional sports game that simulates table tennis. The player controls an in-game paddle by moving it vertically across the left or right side of the screen. They can compete against another player controlling a second paddle on the opposing side.', 'https://upload.wikimedia.org/wikipedia/commons/6/62/Pong_Game_Test2.gif');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (2, 'Zork', 'Adventure', 'Infocom', 'PDP-10', 1977, 'Zork is set in \"the ruins of an ancient empire lying far underground\". The player is a nameless adventurer \"who is venturing into this dangerous land in search of wealth and adventure\". The goal is to return from exploring the \"Great Underground Empire\" (GUE, for short) alive and with all treasures needed to complete each adventure,ultimately inheriting the title of Dungeon Master.', 'https://upload.wikimedia.org/wikipedia/en/a/ac/Zork_I_box_art.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (3, 'Space Invaders', 'Shoot \'em up', 'Taito', 'Arcade', 1978, 'Space Invaders is a fixed shooter in which the player controls a laser cannon by moving it horizontally across the bottom of the screen and firing at descending aliens. ', 'https://upload.wikimedia.org/wikipedia/en/2/20/SpaceInvaders-Gameplay.gif');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (4, 'Asteroids', 'Shoot \'em up', 'Atari', 'Arcade', 1979, 'The objective of Asteroids is to destroy asteroids and saucers. The player controls a triangular ship that can rotate left and right, fire shots straight forward, and thrust forward.', 'https://upload.wikimedia.org/wikipedia/en/8/81/Asteroids-arcadegame.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (5, 'Adventure', 'Action-adventure', 'Atari', 'Atari 2600', 1980, 'In Adventure, the player\'s goal is to recover the Enchanted Chalice that an evil magician has stolen and hidden in the kingdom and return it to the Golden Castle.', 'https://upload.wikimedia.org/wikipedia/en/6/60/Adventure_Box_Front.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (6, 'Missile Command', 'Shoot \'em up', 'Atari', 'Arcade', 1980, 'The game is played by moving a crosshair across the sky background via a trackball and pressing one of three buttons to launch a counter-missile from the appropriate battery.', 'https://upload.wikimedia.org/wikipedia/en/c/c7/Missile_Command_flyer.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (7, 'Pac-Man', 'Maze', 'Namco', 'Arcade', 1980, 'Pac-Man is a maze chase video game; the player controls the eponymous character through an enclosed maze. The objective of the game is to eat all of the dots placed in the maze while avoiding four colored ghosts that pursue him.', 'https://upload.wikimedia.org/wikipedia/en/5/59/Pac-man.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (8, 'Centipede', 'Shoot \'em up', 'Atari', 'Arcade', 1981, 'In the original arcade version: The player\'s fighter is represented by a small insect-like head at the bottom of the screen called the Bug Blaster.', 'https://upload.wikimedia.org/wikipedia/en/6/6b/Centipede-arcade-flyer.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (9, 'Defender', 'Shoot \'em up', 'Williams Entertainment', 'Arcade', 1981, 'Defender is a two-dimensional side-scrolling shooting game set on the surface of an unnamed planet (or, in the Atari VCS version, an unnamed city). ', 'https://upload.wikimedia.org/wikipedia/en/e/ea/Defender_red_label.flyer.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (10, 'Donkey Kong', 'Platform', 'Nintendo', 'Arcade', 1981, 'As the first platform game to feature jumping, Donkey Kong requires the player to jump between gaps and over obstacles or approaching enemies, setting the template for the future of the platform genre.', 'https://upload.wikimedia.org/wikipedia/en/f/fd/Donkey_Kong_Gameplay.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (11, 'Frogger', 'Action', 'Sega', 'Arcade', 1981, 'The objective of the game is to guide a frog to each of the empty \"frog homes\" at the top of the screen.', 'https://upload.wikimedia.org/wikipedia/en/c/cd/Frogger_game_arcade.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (12, 'Galaga', 'Shoot \'em up', 'Namco', 'Arcade', 1981, 'Galaga is a fixed shooter video game. Its plot involves the launch of a starship named the Blast Fighter to destroy the hostile Galaga forces and their home planet.', 'https://upload.wikimedia.org/wikipedia/en/9/9b/Galag88j.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (13, 'Tempest', 'Shoot \'em up', 'Atari', 'Arcade', 1981, 'The goal in Tempest is to survive for as long as possible, and score as many points as possible, by clearing the screen of enemies that appear on the playing field.', 'https://upload.wikimedia.org/wikipedia/en/5/58/Tempest_arcade.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (14, 'Joust', 'Action', 'Williams Entertainment', 'Arcade', 1982, 'The player controls a yellow knight riding a flying ostrich. The player navigates the protagonist around the game world, which consists of rock platforms floating above a flat island surrounded by lava, via two-way joystick and a button. ', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Joustarcadegame.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (15, 'Ms. Pac-Man', 'Maze', 'Midway', 'Arcade', 1982, 'The gameplay is very similar to that of Pac-Man. The player earns points by eating pellets and avoiding monsters (contact with one causes Ms. Pac-Man to lose a life). ', 'https://upload.wikimedia.org/wikipedia/en/4/42/Ms._Pac-Man_flyer.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (16, 'Pitfall!', 'Platform', 'Activision', 'Atari 2600', 1982, 'The player controls Pitfall Harry through 256 horizontally connected screens of jungle in an attempt to recover 32 treasures in a 20-minute time period.', 'https://upload.wikimedia.org/wikipedia/en/0/06/Pitfall%21_Coverart.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (17, 'Robotron: 2084', 'Top-down shooter', 'Williams Entertainment', 'Arcade', 1982, NULL, '');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (18, 'Star Wars', 'Shoot \'em up', 'Atari', 'Arcade', 1983, 'Assuming the role of Luke Skywalker (\"Red Five\"), the player pilots an X-wing fighter from a first-person perspective. ', 'https://upload.wikimedia.org/wikipedia/en/5/5f/Star_wars_gameplay.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (19, 'Elite', 'Space flight simulator', 'Acornsoft', 'BBC Micro', 1984, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (20, 'Marble Madness', 'Action', 'Atari Games', 'Arcade', 1984, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (21, 'Tetris', 'Puzzle', 'Elorg', 'Electronika 60', 1984, 'Tetris is primarily composed of a field of play in which pieces of different geometric forms, called \"tetriminos\", descend from the top of the field.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Tetris_Game_4-Line_Clear.gif/440px-Tetris_Game_4-Line_Clear.gif');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (22, 'Gauntlet', 'Action role-playing', 'Atari Games', 'Arcade', 1985, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (23, 'Ghosts \'n Goblins', 'Platform', 'Capcom', 'Arcade', 1985, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (24, 'Super Mario Bros.', 'Platform', 'Nintendo', 'NES', 1985, 'The objective is to race through the Mushroom Kingdom, survive the main antagonist Bowser\'s forces, and save Princess Toadstool.', 'https://upload.wikimedia.org/wikipedia/en/5/50/NES_Super_Mario_Bros.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (25, 'Bubble Bobble', 'Platform', 'Taito', 'Arcade', 1986, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (26, 'The Legend of Zelda', 'Action-adventure', 'Nintendo', 'NES', 1986, 'The player controls Link from a flip-screen overhead perspective as he travels the overworld, a large outdoor map with various environments', 'https://upload.wikimedia.org/wikipedia/en/3/3a/Legend_of_Zelda_NES.PNG');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (27, 'Out Run', 'Racing', 'Sega', 'Arcade', 1986, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (28, 'Contra', 'Run and gun', 'Konami', 'Arcade', 1987, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (29, 'Double Dragon', 'Beat \'em up', 'Technos Japan', 'Arcade', 1987, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (30, 'Mike Tyson\'s Punch-Out!!', 'Sports', 'Nintendo', 'NES', 1987, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (31, 'R-Type', 'Shoot \'em up', 'Irem', 'Arcade', 1987, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (32, 'Mega Man 2', 'Platform', 'Capcom', 'NES', 1988, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (33, 'Super Mario Bros. 3', 'Platform', 'Nintendo', 'NES', 1988, 'Super Mario Bros. 3 is a two-dimensional, side-scrolling platform game in which the player controls either Mario or Luigi. ', 'https://upload.wikimedia.org/wikipedia/en/a/a5/Super_Mario_Bros._3_coverart.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (34, 'Prince of Persia', 'Platform', 'Broderbund', 'Apple II', 1989, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (35, 'SimCity', 'City-building', 'Maxis', 'Amiga, Macintosh', 1989, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (36, 'The Secret of Monkey Island', 'Adventure', 'LucasArts', 'PC', 1990, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (37, 'Speedball 2: Brutal Deluxe', 'Sports', 'Image Works', 'Atari ST', 1990, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (38, 'Super Mario World', 'Platform', 'Nintendo', 'Super NES', 1990, 'Super Mario World is a side-scrolling platform game in which the player controls Mario or Luigi, the protagonists of the game. The game has similar gameplay to earlier games in the Super Mario series ', 'https://upload.wikimedia.org/wikipedia/en/f/f4/Supermarioworld.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (39, 'Another World', 'Platform', 'Delphine Software', 'Amiga, Atari ST', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (40, 'Civilization', 'Turn-based strategy', 'MicroProse', 'PC', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (41, 'The Legend of Zelda: A Link to the Past', 'Action-adventure', 'Nintendo', 'Super NES', 1991, 'Instead of using the side-scrolling perspective introduced by Zelda II: The Adventure of Link, A Link to the Past reverts to an overhead perspective similar to that of the original The Legend of Zelda. ', 'https://upload.wikimedia.org/wikipedia/en/2/21/The_Legend_of_Zelda_A_Link_to_the_Past_SNES_Game_Cover.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (42, 'Lemmings', 'Puzzle', 'Psygnosis', 'Amiga', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (43, 'Monkey Island 2: LeChuck\'s Revenge', 'Adventure', 'LucasArts', 'PC', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (44, 'Sonic the Hedgehog', 'Platform', 'Sega', 'Sega Genesis', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (45, 'Street Fighter II', 'Fighting', 'Capcom', 'Arcade', 1991, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (46, 'Dune II', 'Real-time strategy', 'Virgin Games', 'PC', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (47, 'Flashback', 'Platform', 'Delphine Software', 'Amiga', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (48, 'Mortal Kombat', 'Fighting', 'Midway', 'Arcade', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (49, 'Sonic the Hedgehog 2', 'Platform', 'Sega', 'Sega Genesis', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (50, 'Super Mario Kart', 'Kart racing', 'Nintendo', 'Super NES', 1992, 'Super Mario Kart is a kart racing game featuring several single and multiplayer modes. During the game, players take control of one of eight Mario franchise characters and drive karts around tracks with a Mario franchise theme. ', 'https://upload.wikimedia.org/wikipedia/en/8/8e/Super_Mario_Kart_screen_shot.jpg');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (51, 'Virtua Racing', 'Racing', 'Sega', 'Arcade', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (52, 'Wolfenstein 3D', 'First-person shooter', 'Apogee Software', 'PC', 1992, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (53, 'Day of the Tentacle', 'Adventure', 'LucasArts', 'PC', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (54, 'Daytona USA', 'Racing', 'Sega', 'Arcade', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (55, 'Doom', 'First-person shooter', 'id Software', 'PC', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (56, 'The Legend of Zelda: Link\'s Awakening', 'Action-adventure', 'Nintendo', 'Game Boy', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (57, 'Mortal Kombat II', 'Fighting', 'Midway', 'Arcade', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (58, 'Myst', 'Adventure', 'Broderbund', 'Macintosh', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (59, 'NBA Jam', 'Sports', 'Midway', 'Arcade', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (60, 'Phantasy Star IV', 'Role-playing', 'Sega', 'Sega Genesis', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (61, 'Sam & Max Hit the Road', 'Adventure', 'LucasArts', 'PC', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (62, 'Secret of Mana', 'Action role-playing', 'Square', 'Super NES', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (63, 'SimCity 2000', 'City-building', 'Maxis', 'Macintosh', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (64, 'Star Fox', 'Shoot \'em up', 'Nintendo', 'Super NES', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (65, 'Syndicate', 'Real-time tactics', 'Electronic Arts', 'Amiga, PC', 1993, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (66, 'Donkey Kong Country', 'Platform', 'Nintendo', 'Super NES', 1994, 'Donkey Kong Country is a side-scrolling platform game in which the player must complete 40 levels to recover the Kongs\' banana hoard, which has been stolen by the crocodilian Kremlings. ', 'https://upload.wikimedia.org/wikipedia/en/3/30/Donkey_Kong_Country_Shot_2.png');
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (67, 'Doom II', 'First-person shooter', 'GT Interactive', 'PC', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (68, 'EarthBound', 'Role-playing', 'Nintendo', 'Super NES', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (69, 'Final Fantasy VI', 'Role-playing', 'Square', 'Super NES', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (70, 'Star Wars: TIE Fighter', 'Space flight simulator', 'LucasArts', 'PC', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (71, 'Super Metroid', 'Action-adventure', 'Nintendo', 'Super NES', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (72, 'UFO: Enemy Unknown', 'Turn-based strategy', 'MicroProse', 'PC', 1994, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (73, 'Chrono Trigger', 'Role-playing', 'Square', 'Super NES', 1995, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (74, 'Command & Conquer', 'Real-time strategy', 'Virgin Interactive', 'PC', 1995, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (75, 'Warcraft II: Tides of Darkness', 'Real-time strategy', 'Blizzard Entertainment', 'PC', 1995, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (76, 'Wipeout', 'Racing', 'Psygnosis', 'PC, PlayStation', 1995, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (77, 'Yoshi\'s Island', 'Platform', 'Nintendo', 'Super NES', 1995, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (78, 'Civilization II', 'Turn-based strategy', 'MicroProse', 'PC', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (79, 'Command & Conquer: Red Alert', 'Real-time strategy', 'Virgin Interactive', 'PC', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (80, 'Duke Nukem 3D', 'First-person shooter', 'GT Interactive', 'PC', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (81, 'Nights into Dreams...', 'Action', 'Sega', 'Sega Saturn', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (82, 'PaRappa the Rapper', 'Rhythm', 'Sony Computer Entertainment', 'PlayStation', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (83, 'Pokémon Red and Blue', 'Role-playing', 'Nintendo', 'Game Boy', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (84, 'Quake', 'First-person shooter', 'GT Interactive', 'PC', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (85, 'Resident Evil', 'Survival horror', 'Capcom', 'PlayStation', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (86, 'Super Mario 64', 'Platform', 'Nintendo', 'Nintendo 64', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (87, 'Tomb Raider', 'Action-adventure', 'Eidos Interactive', 'Sega Saturn, PlayStation', 1996, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (88, 'Castlevania: Symphony of the Night', 'Action-adventure', 'Konami', 'PlayStation', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (89, 'Diablo', 'Action role-playing', 'Blizzard Entertainment', 'PC', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (90, 'Fallout', 'Role-playing', 'Interplay Entertainment', 'PC', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (91, 'Final Fantasy Tactics', 'Tactical role-playing', 'Square', 'PlayStation', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (92, 'Final Fantasy VII', 'Role-playing', 'Square', 'PlayStation', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (93, 'GoldenEye 007', 'First-person shooter', 'Nintendo', 'Nintendo 64', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (94, 'Gran Turismo', 'Racing', 'Sony Computer Entertainment', 'PlayStation', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (95, 'Quake II', 'First-person shooter', 'Activision', 'PC', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (96, 'Star Fox 64', 'Shoot \'em up', 'Nintendo', 'Nintendo 64', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (97, 'Star Wars Jedi Knight: Dark Forces II', 'First-person shooter', 'LucasArts', 'PC', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (98, 'Tekken 3', 'Fighting', 'Namco', 'Arcade', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (99, 'Ultima Online', 'MMORPG', 'Electronic Arts', 'PC', 1997, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (100, 'Dance Dance Revolution', 'Rhythm', 'Konami', 'Arcade', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (101, 'Fallout 2', 'Role-playing', 'Interplay Entertainment', 'PC', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (102, 'Grim Fandango', 'Adventure', 'LucasArts', 'PC', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (103, 'Half-Life', 'First-person shooter', 'Sierra Studios', 'PC', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (104, 'The Legend of Zelda: Ocarina of Time', 'Action-adventure', 'Nintendo', 'Nintendo 64', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (105, 'Metal Gear Solid', 'Stealth', 'Konami', 'PlayStation', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (106, 'Panzer Dragoon Saga', 'Role-playing', 'Sega', 'Sega Saturn', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (107, 'Resident Evil 2', 'Survival horror', 'Capcom', 'PlayStation', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (108, 'Soulcalibur', 'Fighting', 'Namco', 'Arcade', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (109, 'StarCraft', 'Real-time strategy', 'Blizzard Entertainment', 'PC', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (110, 'Thief: The Dark Project', 'Stealth', 'Eidos Interactive', 'PC', 1998, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (111, 'Age of Empires II', 'Real-time strategy', 'Microsoft', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (112, 'EverQuest', 'MMORPG', 'Sony Online Entertainment', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (113, 'Homeworld', 'Real-time strategy', 'Sierra Studios', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (114, 'Planescape: Torment', 'Role-playing', 'Interplay Entertainment', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (115, 'Quake III: Arena', 'First-person shooter', 'Activision', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (116, 'Shenmue', 'Adventure', 'Sega', 'Dreamcast', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (117, 'Silent Hill', 'Survival horror', 'Konami', 'PlayStation', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (118, 'System Shock 2', 'First-person shooter', 'Electronic Arts', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (119, 'Unreal Tournament', 'First-person shooter', 'GT Interactive', 'PC', 1999, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (120, 'Baldur\'s Gate II: Shadows of Amn', 'Role-playing', 'Black Isle Studios', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (121, 'Counter-Strike', 'First-person shooter', 'Valve', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (122, 'Deus Ex', 'Action role-playing', 'Eidos Interactive', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (123, 'Diablo II', 'Action role-playing', 'Blizzard Entertainment', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (124, 'Jet Set Radio', 'Platform', 'Sega', 'Dreamcast', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (125, 'The Legend of Zelda: Majora\'s Mask', 'Action-adventure', 'Nintendo', 'Nintendo 64', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (126, 'The Sims', 'Life simulation', 'Electronic Arts', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (127, 'Thief II: The Metal Age', 'Stealth', 'Eidos Interactive', 'PC', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (128, 'Tony Hawk\'s Pro Skater 2', 'Sports', 'Activision', 'PlayStation', 2000, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (129, 'Advance Wars', 'Turn-based tactics', 'Nintendo', 'Game Boy Advance', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (130, 'Animal Crossing', 'Life simulation', 'Nintendo', 'GameCube', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (131, 'Devil May Cry', 'Action-adventure', 'Capcom', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (132, 'Final Fantasy X', 'Role-playing', 'Square', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (133, 'Gran Turismo 3: A-Spec', 'Racing', 'Sony Computer Entertainment', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (134, 'Grand Theft Auto III', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (135, 'Halo: Combat Evolved', 'First-person shooter', 'Microsoft Game Studios', 'Xbox', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (136, 'Ico', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (137, 'Ikaruga', 'Shoot \'em up', 'Treasure', 'Arcade', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (138, 'Max Payne', 'Third-person shooter', 'Gathering of Developers', 'PC', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (139, 'Metal Gear Solid 2: Sons of Liberty', 'Stealth', 'Konami', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (140, 'Rez', 'Shoot \'em up', 'Sega', 'Dreamcast, PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (141, 'Silent Hill 2', 'Survival horror', 'Konami', 'PlayStation 2', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (142, 'Super Smash Bros. Melee', 'Fighting', 'Nintendo', 'GameCube', 2001, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (143, 'The Elder Scrolls III: Morrowind', 'Action role-playing', 'Bethesda Softworks', 'PC', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (144, 'Grand Theft Auto: Vice City', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (145, 'Kingdom Hearts', 'Action role-playing', 'Squaresoft', 'PlayStation 2', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (146, 'The Legend of Zelda: The Wind Waker', 'Action-adventure', 'Nintendo', 'GameCube', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (147, 'Metroid Prime', 'Action-adventure', 'Nintendo', 'GameCube', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (148, 'Soulcalibur II', 'Fighting', 'Namco', 'Arcade', 2002, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (149, 'Beyond Good & Evil', 'Action-adventure', 'Ubisoft', 'PlayStation 2', 2003, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (150, 'Max Payne 2', 'Third-person shooter', 'Rockstar Games', 'PC', 2003, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (151, 'Prince of Persia: The Sands of Time', 'Action-adventure', 'Ubisoft', 'PlayStation 2', 2003, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (152, 'Star Wars: Knights of the Old Republic', 'Role-playing', 'LucasArts', 'Xbox', 2003, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (153, 'WarioWare, Inc.: Mega Microgames!', 'Action', 'Nintendo', 'Game Boy Advance', 2003, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (154, 'Burnout 3: Takedown', 'Racing', 'Electronic Arts', 'PlayStation 2, Xbox', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (155, 'Dragon Quest VIII', 'Role-playing', 'Square Enix', 'PlayStation 2', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (156, 'Grand Theft Auto: San Andreas', 'Action-adventure', 'Rockstar Games', 'PlayStation 2', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (157, 'Half-Life 2', 'First-person shooter', 'Valve', 'PC', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (158, 'Halo 2', 'First-person shooter', 'Microsoft Game Studios', 'Xbox', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (159, 'Katamari Damacy', 'Action', 'Namco', 'PlayStation 2', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (160, 'Metal Gear Solid 3: Snake Eater', 'Stealth', 'Konami', 'PlayStation 2', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (161, 'Rome: Total War', 'Strategy', 'Activision', 'PC', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (162, 'World of Warcraft', 'MMORPG', 'Blizzard Entertainment', 'PC', 2004, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (163, 'Civilization IV', 'Turn-based strategy', '2K Games', 'PC', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (164, 'Devil May Cry 3: Dante\'s Awakening', 'Action-adventure', 'Capcom', 'PlayStation 2', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (165, 'God of War', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (166, 'Guitar Hero', 'Rhythm', 'RedOctane', 'PlayStation 2', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (167, 'Psychonauts', 'Platform', 'Majesco', 'PC', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (168, 'Resident Evil 4', 'Survival horror', 'Capcom', 'GameCube', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (169, 'Shadow of the Colossus', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (170, 'Tom Clancy\'s Splinter Cell: Chaos Theory', 'Stealth', 'Ubisoft', 'GameCube, PC, PlayStation 2, Xbox', 2005, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (171, 'Company of Heroes', 'Real-time strategy', 'THQ', 'PC', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (172, 'The Elder Scrolls IV: Oblivion', 'Role-playing', 'Bethesda Softworks', 'PC, Xbox 360', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (173, 'Gears of War', 'Third-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (174, 'Hitman: Blood Money', 'Stealth', 'Eidos Interactive', 'PC, PlayStation 2, Xbox, Xbox 360', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (175, 'Ōkami', 'Action-adventure', 'Capcom', 'PlayStation 2', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (176, 'Wii Sports', 'Sports', 'Nintendo', 'Wii', 2006, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (177, 'BioShock', 'First-person shooter', '2K Games', 'PC, Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (178, 'Call of Duty 4: Modern Warfare', 'First-person shooter', 'Activision', 'PC, PlayStation 3, Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (179, 'God of War II', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 2', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (180, 'Halo 3', 'First-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (181, 'Mass Effect', 'Action role-playing', 'Microsoft Game Studios', 'Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (182, 'Portal', 'Puzzle-platformer', 'Valve', 'PC, Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (183, 'Rock Band', 'Rhythm', 'MTV Games', 'PlayStation 3, Xbox 360', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (184, 'Super Mario Galaxy', 'Platform', 'Nintendo', 'Wii', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (185, 'Team Fortress 2', 'First-person shooter', 'Valve', 'PC', 2007, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (186, 'Braid', 'Puzzle-platformer', 'Microsoft Game Studios', 'Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (187, 'Burnout Paradise', 'Racing', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (188, 'Dead Space', 'Survival horror', 'Electronic Arts', 'PlayStation 3, Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (189, 'Fallout 3', 'Action role-playing', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (190, 'Gears of War 2', 'Third-person shooter', 'Microsoft Game Studios', 'Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (191, 'Grand Theft Auto IV', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (192, 'Left 4 Dead', 'First-person shooter', 'Valve', 'PC', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (193, 'LittleBigPlanet', 'Platform', 'Sony Computer Entertainment', 'PlayStation 3', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (194, 'Persona 4', 'Role-playing', 'Atlus', 'PlayStation 2', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (195, 'Rock Band 2', 'Rhythm', 'MTV Games', 'Xbox 360', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (196, 'Spelunky', 'Platform', 'Derek Yu', 'PC', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (197, 'Street Fighter IV', 'Fighting', 'Capcom', 'Arcade', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (198, 'Valkyria Chronicles', 'Tactical role-playing', 'Sega', 'PlayStation 3', 2008, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (199, 'Assassin\'s Creed II', 'Action-adventure', 'Ubisoft', 'PlayStation 3, Xbox 360', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (200, 'Batman: Arkham Asylum', 'Action-adventure', 'Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (201, 'Bayonetta', 'Action', 'Sega', 'PlayStation 3, Xbox 360', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (202, 'Dragon Age: Origins', 'Role-playing', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (203, 'Left 4 Dead 2', 'First-person shooter', 'Valve', 'PC, Xbox 360', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (204, 'Uncharted 2: Among Thieves', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2009, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (205, 'Limbo', 'Platform', 'Microsoft Game Studios', 'Xbox 360', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (206, 'Mass Effect 2', 'Action role-playing', 'Electronic Arts', 'PC, Xbox 360', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (207, 'Red Dead Redemption', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (208, 'Rock Band 3', 'Rhythm', 'MTV Games', 'PlayStation 3, Xbox 360, Wii, Nintendo DS', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (209, 'StarCraft II: Wings of Liberty', 'Real-time strategy', 'Blizzard Entertainment', 'PC', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (210, 'Super Mario Galaxy 2', 'Platform', 'Nintendo', 'Wii', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (211, 'Super Meat Boy', 'Platform', 'Team Meat', 'Xbox 360', 2010, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (212, 'Batman: Arkham City', 'Action-adventure', 'Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2011, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (213, 'Dark Souls', 'Action role-playing', 'Namco Bandai Games', 'PlayStation 3, Xbox 360', 2011, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (214, 'The Elder Scrolls V: Skyrim', 'Action role-playing', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2011, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (215, 'Minecraft', 'Sandbox', 'Mojang', 'PC', 2011, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (216, 'Portal 2', 'Puzzle-platformer', 'Valve', 'PC, PlayStation 3, Xbox 360', 2011, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (217, 'Dishonored', 'Stealth', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2012, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (218, 'Journey', 'Adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2012, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (219, 'The Walking Dead', 'Adventure', 'Telltale Games', 'PC, PlayStation 3, Xbox 360', 2012, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (220, 'Dota 2', 'MOBA', 'Valve', 'PC', 2013, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (221, 'Grand Theft Auto V', 'Action-adventure', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2013, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (222, 'The Last of Us', 'Action-adventure', 'Sony Computer Entertainment', 'PlayStation 3', 2013, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (224, 'Bloodborne', 'Action role-playing', 'Sony Computer Entertainment', 'PlayStation 4', 2015, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (225, 'The Witcher III: Wild Hunt', 'Action role-playing', 'CD Projekt', 'PC, PlayStation 4, Xbox One', 2015, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (226, 'Inside', 'Platform', 'Playdead', 'Xbox One', 2016, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (227, 'Overwatch', 'First-person shooter', 'Blizzard Entertainment', 'PC, PlayStation 4, Xbox One', 2016, NULL, NULL);
INSERT INTO `game` (`id`, `name`, `genre`, `publisher`, `original_platform`, `released_year`, `description`, `image`) VALUES (228, 'The Legend of Zelda: Breath of the Wild', 'Action-adventure', 'Nintendo', 'Nintendo Switch, Wii U', 2017, NULL, NULL);

COMMIT;

